[package]
name = "faces_network_common_types"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.226"
serde_json = "1.0.145"
faces_quic_client = { git = "https://github.com/Cm3lp8/faces-quic-client.git", optional = true}
uuid = {version = "1.18.1", features = ["v4", "v7", "serde"]}


